### ISSUE TITLE
Undo for Deletion or Confirmation when killing a filter

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/RefinedRelocation2#54]
Right now your hours of work setting up a beautiful filter configuration is just gone if you misclick.

**Comment by JohnTravolta76** [comment]
Again not a coder, but i mess with NBTEdit and shit, but what I think you can do (from my understanding of what you are wanting) In the NBT data have a "history" list of previous filter configurations, so that way if you press undo it will retrieve it from the History tag and put it back into the other data tag?
